  - name: Install MySQL
    apt:
      name: python-mysqldb, mysql-server

  - name: Start the MySQL service
    service: 
      name: mysql 
      state: started
      enabled: true

  - name: Enable Remote access
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: 'bind-address'
      line: bind-address = 0.0.0.0

  - name: Restart Mysql
    shell: /etc/init.d/mysql restart